### ISSUE TITLE
How to deal with (Sexp e1) :: stmts case when evaluating functions 

### ISSUE THREAD

**Issue by jakezweifler** [LambdaQs/arrays#9]
One case that comes up is when there is an expression followed by other statements. If the expression was pure, then its presence in the code would have no effect so it could just be ignored. However, a classical expression could also be impure. An example of this is in ImpureClassicalExample.qs. I am thinking of adding another expression to the LQS grammar that holds these impure expressions that would be like "do" exp "in" exp. We could also just use let statements where the variable is a wildcard. How should this case be dealt with?

**Comment by k4rtik** [comment]
I see `ImpureClassicalExample.qs` is:
```qsharp
namespace ImpureClassicalExample {
    open Microsoft.Quantum.Intrinsic;

    function Tail<'A> (array : 'A[]) : 'A {
        EqualityFactB(Length(array) > 0, true, $"Array must be of the length at least 1");
        return array[Length(array) - 1];
    }

}
```

Which part of it is impure?

EDIT: I see that you were referring to the printing of the string in the `EqualityFactB` call. We can ignore that for now.
